services:
  - type: web
    name: garbage-classification
    env: docker
    branch: main
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: DEBUG
        value: false
      - key: MODEL_PATH
        value: /app/garbage_classification_model.h5
    autoDeploy: true